version: "3"
services:
  protoc:
    build:
      context: .
      dockerfile: "protoc.Dockerfile"
      args:
        - "ARCH=${ARCH:-x86_64}"
    platform: linux/arm64
    volumes:
      - ".:/ts-proto"
      - "${PWD:-.}:/host"
